---
- hosts: localhost
  vars:
    user_name: prueba
    new_password:universidad
  
  tasks:
  - name: 'Cambiar password'
    become: true
    user: 
      name: '{{ user_name }}'
      password: '{{ new_password | password_hash("sha512") }}'
      update_password: 'always'
